### ISSUE TITLE
Change on screen notifications from boxes to listed in a bell icon?

### ISSUE THREAD

**Issue by ChrisKendallVA** [CommanderStorm/uptime-kuma#3]
### 📑 I have found these related issues/pull requests

When updating/restarting a server with 500+ connections the pop up notifications block the settings section at the top restricting you from being able to administer the server when necessary.pop-up

### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Change the pop-up notification boxes to a Bell Icon at the top of the page 

### ✔️ Solution

when the bell icon is clicked it can give a drop-down of the notifications. This will clean up the dashboard from excessive notifications upon restart

### ❓ Alternatives

Stack the notifications and reduce the display time to 1-2 seconds as to not fill the whole side of the screen up

### 📝 Additional Context

Nothing that i can think of

**Comment by CommanderStorm** [comment]
@ChrisKendallVA
did you mean to submit this issue on a fork of the project?
I can't move this to louislam/uptime-kuma as I am not an owner there, but please open issues against the correct repo instead.

Closing as this is the wrong repository
